// Generated by CoffeeScript 1.6.3
(function() {
  define({
    LIVEBLOG_URL: 'http://master.sd-test.sourcefabric.org/resources/LiveDesk/Blog/1/Post/Published/?X-Filter=*&limit=1000'
  });

}).call(this);
