// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    paths: {
      jquery: '../bower_components/jquery/jquery.min',
      underscore: '../node_modules/underscore/underscore-min',
      backbone: '../node_modules/backbone/backbone-min',
      text: '../node_modules/text/text',
      templates: '../templates'
    },
    shim: {
      underscore: {
        exports: '_'
      },
      backbone: {
        deps: ['underscore', 'jquery'],
        exports: 'Backbone'
      }
    }
  });

  require(['router'], function(Router) {
    return $(function() {
      var router;
      router = new Router();
      return Backbone.history.start({
        pushState: true
      });
    });
  });

}).call(this);
