// Generated by CoffeeScript 1.6.3
(function() {
  define(['backbone', 'views/blog', 'collections/posts', 'views/posts'], function(Backbone, BlogView, Posts, PostsView) {
    return Backbone.Router.extend({
      routes: {
        '*path': 'default'
      },
      "default": function(path) {
        var posts, postsView;
        posts = new Posts();
        postsView = new PostsView({
          collection: posts
        });
        postsView.render();
        return posts.fetch();
      }
    });
  });

}).call(this);
