// Generated by CoffeeScript 1.6.3
(function() {
  define(['backbone', 'views/blog'], function(Backbone, BlogView) {
    return Backbone.Router.extend({
      routes: {
        '*path': 'default'
      },
      "default": function(path) {
        var blogView;
        blogView = new BlogView();
        return $('.root').html(blogView.render().$el);
      }
    });
  });

}).call(this);
