// Generated by CoffeeScript 1.6.3
(function() {
  var LIVEBLOG_URL, app, dust, express, request, requirejs;

  requirejs = require('requirejs');

  express = require('express');

  dust = require('dustjs-linkedin');

  request = require('request');

  LIVEBLOG_URL = 'http://master.sd-test.sourcefabric.org/resources/LiveDesk/Blog/1/Post/Published/?X-Filter=*&limit=1000';

  app = express();

  app.configure(function() {
    return app.use(express["static"](__dirname + '/..'));
  });

  requirejs.config({
    paths: {
      templates: '../templates'
    },
    packages: [
      {
        name: 'text',
        location: '../node_modules/text',
        main: 'text.js'
      }
    ],
    nodeRequire: require
  });

  requirejs(['models/blog', 'collections/posts', 'text!templates/blog.tmpl', 'text!templates/post.tmpl'], function(Blog, Posts, BlogTmpl, PostTmpl) {
    var objects, port;
    objects = {
      blog: new Blog()
    };
    app.get('/', function(req, res) {
      return request(LIVEBLOG_URL, function(error, response, data) {
        if (!error && response.statusCode === 200) {
          objects.posts = new Posts(JSON.parse(data), {
            parse: true
          });
          dust.loadSource(dust.compile(PostTmpl, 'post'));
          return dust.render('post', objects.posts.first().toJSON(), function(err, out) {
            return res.send(out);
          });
        }
      });
    });
    port = 3000;
    return app.listen(port, function() {
      return console.log('Listening on port %d', port);
    });
  });

}).call(this);
