// Generated by CoffeeScript 1.6.3
(function() {
  define(['backbone', 'dust', 'text!templates/post.tmpl'], function(Backbone, Dust, PostTmpl) {
    return Backbone.View.extend({
      el: '.root',
      initialize: function() {
        dust.loadSource(dust.compile(PostTmpl, 'postTmpl'));
        this.listenTo(this.collection, 'reset', this.render);
        this.listenTo(this.collection, 'sync', this.render);
        return this.listenTo(this.collection, 'change', this.render);
      },
      render: function() {
        this.$el.empty();
        this.collection.forEach(this.renderPost, this);
        return this;
      },
      renderPost: function(post) {
        var self;
        self = this;
        return dust.render('postTmpl', post.toJSON(), function(err, out) {
          return self.$el.append(out);
        });
      }
    });
  });

}).call(this);
