// Generated by CoffeeScript 1.6.3
(function() {
  define(['Backbone'], function(Backbone) {
    return Backbone.Model.extend({
      defaults: {
        name: 'My Blog'
      }
    });
  });

}).call(this);
