// Generated by CoffeeScript 1.6.3
(function() {
  define(['backbone', 'models/post'], function(Backbone, Post) {
    return Backbone.Collection.extend({
      model: Post,
      url: 'http://master.sd-test.sourcefabric.org/resources/LiveDesk/Blog/1/Post/Published/?X-Filter=*&limit=1000',
      parse: function(data) {
        return data.PostList;
      }
    });
  });

}).call(this);
